export type ShippingOption = "standard" | "express";

export const SHIPPING_OPTIONS: Record<
  ShippingOption,
  { label: string; price: number; description: string; delivery: string }
> = {
  standard: {
    label: "Standard Delivery",
    price: 39,
    description: "Tracked postal service",
    delivery: "7–12 business days",
  },
  express: {
    label: "Priority Galactic Launch",
    price: 49,
    description: "DHL/DPD tracked courier · Priority processing",
    delivery: "2–4 business days",
  },
};

export const PHONE_MODELS: string[] = [
  // iPhone (newest first)
  "iPhone 17 Pro Max",
  "iPhone 17 Pro",
  "iPhone 17 Air",
  "iPhone 17e",
  "iPhone 17",
  "iPhone 16 Pro Max",
  "iPhone 16 Pro",
  "iPhone 16 Plus",
  "iPhone 16e",
  "iPhone 16",
  "iPhone 15 Pro Max",
  "iPhone 15 Pro",
  "iPhone 15 Plus",
  "iPhone 15",
  "iPhone 14 Pro Max",
  "iPhone 14 Pro",
  "iPhone 14 Plus",
  "iPhone 14",
  "iPhone 13 Pro Max",
  "iPhone 13 Pro",
  "iPhone 13 Mini",
  "iPhone 13",
  "iPhone 12 Pro Max",
  "iPhone 12 Pro",
  "iPhone 12 Mini",
  "iPhone 12",
  "iPhone 11 Pro Max",
  "iPhone 11 Pro",
  "iPhone 11",
  "iPhone SE (2022)",
  "iPhone SE (2020)",
  "iPhone XS Max",
  "iPhone XS",
  "iPhone XR",
  "iPhone X",
  "iPhone 8 Plus",
  "iPhone 8",
  "iPhone 7 Plus",
  "iPhone 7",
  // Samsung Galaxy — S
  "Samsung Galaxy S26 Ultra",
  "Samsung Galaxy S26 Plus",
  "Samsung Galaxy S26",
  "Samsung Galaxy S25 Ultra",
  "Samsung Galaxy S25 Plus",
  "Samsung Galaxy S25",
  "Samsung Galaxy S24 Ultra",
  "Samsung Galaxy S24 Plus",
  "Samsung Galaxy S24 FE",
  "Samsung Galaxy S24",
  "Samsung Galaxy S23 Ultra",
  "Samsung Galaxy S23 Plus",
  "Samsung Galaxy S23 FE",
  "Samsung Galaxy S23",
  "Samsung Galaxy S22 Ultra",
  "Samsung Galaxy S22 Plus",
  "Samsung Galaxy S22",
  "Samsung Galaxy S21 Ultra",
  "Samsung Galaxy S21 Plus",
  "Samsung Galaxy S21 FE",
  "Samsung Galaxy S21",
  "Samsung Galaxy S20 Ultra",
  "Samsung Galaxy S20 Plus",
  "Samsung Galaxy S20 FE",
  "Samsung Galaxy S20",
  "Samsung Galaxy S10 Plus",
  "Samsung Galaxy S10e",
  "Samsung Galaxy S10 Lite",
  "Samsung Galaxy S10",
  "Samsung Galaxy S9 Plus",
  "Samsung Galaxy S9",
  "Samsung Galaxy S8 Plus",
  "Samsung Galaxy S8",
  // Samsung Galaxy — A
  "Samsung Galaxy A73",
  "Samsung Galaxy A72 5G",
  "Samsung Galaxy A72 4G",
  "Samsung Galaxy A71",
  "Samsung Galaxy A55",
  "Samsung Galaxy A54 5G",
  "Samsung Galaxy A53 5G",
  "Samsung Galaxy A52s",
  "Samsung Galaxy A52",
  "Samsung Galaxy A51",
  "Samsung Galaxy A42",
  "Samsung Galaxy A35",
  "Samsung Galaxy A34",
  "Samsung Galaxy A33 5G",
  "Samsung Galaxy A32",
  "Samsung Galaxy A26",
  "Samsung Galaxy A25",
  "Samsung Galaxy A23 5G",
  "Samsung Galaxy A23 4G",
  "Samsung Galaxy A22",
  "Samsung Galaxy A17",
  "Samsung Galaxy A16",
  "Samsung Galaxy A15",
  "Samsung Galaxy A14 5G",
  "Samsung Galaxy A13",
  "Samsung Galaxy A12",
  "Samsung Galaxy A03s",
  "Samsung Galaxy A03",
  "Samsung Galaxy A10",
  // Samsung Galaxy — Note
  "Samsung Galaxy Note 20 Ultra",
  "Samsung Galaxy Note 20",
  "Samsung Galaxy Note 10 Plus",
  "Samsung Galaxy Note 10",
  "Samsung Galaxy Note 9",
  "Samsung Galaxy Note 8",
  // Samsung Galaxy — Z
  "Samsung Galaxy Z Fold 6",
  "Samsung Galaxy Z Fold 5",
  "Samsung Galaxy Z Fold 4",
  "Samsung Galaxy Z Fold 3",
  "Samsung Galaxy Z Flip 7 FE",
  "Samsung Galaxy Z Flip 6 FE",
  "Samsung Galaxy Z Flip 5",
  "Samsung Galaxy Z Flip 4",
  "Samsung Galaxy Z Flip 3",
  // Xiaomi
  "Xiaomi 15 Pro",
  "Xiaomi 15",
  "Xiaomi 14 Ultra",
  "Xiaomi 14T Pro",
  "Xiaomi 14T",
  "Xiaomi 14 Pro",
  "Xiaomi 14",
  "Xiaomi 13 Ultra",
  "Xiaomi 13T Pro",
  "Xiaomi 13T",
  "Xiaomi 13 Pro",
  "Xiaomi 13 Lite",
  "Xiaomi 13",
  // Mi
  "Mi 12T Pro",
  "Mi 12T",
  "Mi 11 Lite 5G NE",
  "Mi 11 Lite 5G",
  "Mi 11 Lite 4G",
  // Redmi Note
  "Redmi Note 14 Pro+ 5G",
  "Redmi Note 14 Pro",
  "Redmi Note 14",
  "Redmi Note 13 Pro+ 5G",
  "Redmi Note 13 Pro",
  "Redmi Note 13",
  "Redmi Note 12 Pro+ 5G",
  "Redmi Note 12 Pro",
  "Redmi Note 12",
  "Redmi Note 11T Pro",
  "Redmi Note 11T",
  "Redmi Note 11 Pro+",
  "Redmi Note 11 Pro",
  "Redmi Note 11",
  // Google Pixel
  "Google Pixel 9 Pro XL",
  "Google Pixel 9 Pro",
  "Google Pixel 9",
  "Google Pixel 8 Pro",
  "Google Pixel 8a",
  "Google Pixel 8",
  "Google Pixel 7 Pro",
  "Google Pixel 7a",
  "Google Pixel 7",
  "Google Pixel 6 Pro",
  "Google Pixel 6a",
  "Google Pixel 6",
  // OnePlus
  "OnePlus 12",
  "OnePlus 12R",
  "OnePlus 11",
  "OnePlus 10 Pro 5G",
  "OnePlus Ace Pro",
  "OnePlus 9 Pro",
  "OnePlus 9",
  "OnePlus 8 Pro",
  "OnePlus 8",
  // Huawei & Motorola
  "Huawei P30 Lite",
  "Huawei P30",
  "Motorola Moto G Power 2021",
];

function isXiaomiFamilyModel(model: string): boolean {
  return (
    model.startsWith("Xiaomi") ||
    model.startsWith("Mi ") ||
    model.startsWith("Redmi")
  );
}

export const PHONE_MODEL_GROUPS: { label: string; models: string[] }[] = [
  {
    label: "Apple iPhone",
    models: PHONE_MODELS.filter((model) => model.startsWith("iPhone")),
  },
  {
    label: "Samsung Galaxy",
    models: PHONE_MODELS.filter((model) => model.startsWith("Samsung")),
  },
  {
    label: "Xiaomi / Redmi",
    models: PHONE_MODELS.filter(isXiaomiFamilyModel),
  },
  {
    label: "Google Pixel",
    models: PHONE_MODELS.filter((model) => model.startsWith("Google")),
  },
  {
    label: "OnePlus",
    models: PHONE_MODELS.filter((model) => model.startsWith("OnePlus")),
  },
  {
    label: "Huawei",
    models: PHONE_MODELS.filter((model) => model.startsWith("Huawei")),
  },
  {
    label: "Motorola",
    models: PHONE_MODELS.filter((model) => model.startsWith("Motorola")),
  },
];
